// Minimal ambient type declarations for Laravel Wayfinder virtual modules
// These are provided at runtime by the Vite plugin, but TypeScript needs module types.

declare module 'routes' {
    // Exported functions map to named routes. These names are used in the app.
    export const dashboard: any;
    export const login: any;
    export const register: any;
    export const logout: any;
    export const home: any;
    export const appearance: any;
}

declare module 'routes/*' {
    // Route groups like 'routes/profile', 'routes/password', 'routes/verification'
    export const edit: any;
    export const send: any;
    export const request: any;
}

declare module 'actions/*' {
    // Server action endpoints generated by Wayfinder
    const actions: any;
    export default actions;
}


